### ISSUE TITLE
Support firmware 3.a1

### ISSUE THREAD

**Issue by doudz** [doudz/zigate#141]
- [x] Add Raw Mode, command 0x0002 (zigpy )
- [x] Add PDM migration for version changing
- [x] Add support of cluster IAS_WD (0x0502). To manage alarm siren
- [ ] Add Flow control (RTS/CTS) option control
- [x] Add SrcAddr to 0x804A command (MANAGEMENT_NETWORK_UPDATE_RESPONSE) 
- [x] Add SrcAddr to 0x804E command (MANAGEMENT_LQI_REQUEST) 
- [x] Add fields for 0x8030, 0x8031 Both responses now include source endpoint, addressmode and short address. 
- [ ] Add TERNCY devices (talk to 0x6E endpoint and use private cluster 0xFCCC)
- [x] Add KONKE devices (talk to 0x15 endpoint)
- [ ] Add complete INNR RC110 support (add LEVEL_CONTROL_SERVER)  + 
- [ ] Add 0x40 command on Cluster (0x0006) (for INNR RC110)
- [ ] Add 0x04 an 0x02 command on Cluster (0x0008) (for INNR RC110)
- [x] Add cmd 0x0111 E_SL_MSG_WRITE_ATTRIBUTE_REQUEST_IAS_WD to send command to IAS_WD device
- [x] Add cmd 0x0112 E_SL_MSG_WRITE_ATTRIBUTE_REQUEST_IAS_WD_SQUAWK to send command to IAS_WD device
- [x] Add cmd 0x0807 Get Tx Power 
- [x] Add response 0x8806 Set Tx Power and 0x8807 get tx power response
- [ ] Add BMAP16 attribute type 
- [x] Fix Rearranged teNODE_STATES to logical in all cases 
- [x] Fix Changed 8702 to respect address mode  + 
- [x] Fix Command 0x8024 returns addr, ieee and channel with status 4 
- [x] Fix issue to manage Address Mode with APS_DATA_CONFIRM
- [x] Fix issues with MultiStateInputBasicClient
- [x] Remove Identify server
- [x] Remove Multistate_Input_Basic server
- [x] Remove Analog Input basic server
- [x] Remove double case and tidying code ZPS_ZDP_MGMT_LEAVE_RSP_CLUSTER_ID was checked twice.

**Comment by ruimarinho** [comment]
@doudz do you think it's time to migrate from `doudz/home-assistant` to native zha home-assistant integration with the current state of 3.1a support and zigpy device plugin?

**Comment by doudz** [comment]
@ruimarinho zha is ready to use
but I will keep the custom component since it will provide other functionnalities like zigate firmware upgrade or network map which aren't available in zha
