### ISSUE TITLE
Command 0x0009 failed Unhandled command : b''

### ISSUE THREAD

**Issue by chpeps** [doudz/zigate#15]
j'ai ce message d'erreur à chaque démarrage de mon script python, qui fait juste :

`import zigate`
`z = zigate.ZiGate(port=None)`
`print(z.get_version())`

après tous semble fonctionner correctement.

Message d'erreur:
`Command 0x0009 failed Unhandled command : b''`
`No response waiting command 0x8009`
`Failed to get network state`
`No response waiting command 0x8024`
`Command 0x0015 failed Unhandled command : b''`
`No response waiting command 0x8015`
`OrderedDict([('major', 1), ('installer', '30'), ('rssi', 0), ('version', '3.0')])`

j'ai effectuer des tests avec l'interface officel de test de Zigate sur le "get network state":
`11:49:44.937 -> 01 02 10 02 19 02 10 02 10 02 19 03 `
`11:49:45.000 <- 01 80 00 00 05 8E 02 00 00 09 00 03`

**Comment by doudz** [comment]
Il faut mettre à jour le firmware de la zigate à la version 3.0d
