### ISSUE TITLE
Interrupteur Volets Roulants

### ISSUE THREAD

**Issue by Theandone90** [doudz/zigate#166]
Je viens d'installer plusieurs interrupteur volets roulants Celiane.
Ma Zigate détecte bien les interrupteurs, mais impossible de récupérer l'état des volets (ouvert/fermer);
Savez-vous s'il es possible de récupérer cette information ?

**Comment by doudz** [comment]
Il me semble que ce n'est simplement pas possible car il n'y a pas de retour d'information entre le volet et l'interrupteur.
Est ce que je pourrais avoir le modèle de l'interrupteur pour vérifier ?

**Comment by Theandone90** [comment]
réf legrand : 0 677 26
Interrupteur filaire connecté Céliane with Netatmo pour volet roulant - blanc

**Comment by doudz** [comment]
Je confirme, pas de possibilité de connaitre l'état réel du volet
