### ISSUE TITLE
Popin santé

### ISSUE THREAD

**Issue by llaumgui** [doudz/zigate#17]
Bonjour,

Pour faciliter la maintenance, une page de santé remontant les dernières dates de communication, la qualité de réception, les piles, etc... le tout par équipement serait appréciable.
De même certaines infos pourraient figurer directement dans la page équipement, à la manière des plugins ZWave et RFX.

**Comment by doudz** [comment]
Mauvais endroit ce dépot gère la librairie zigate utilisé par le plugin Jeedom, pas le plugin en lui même.
Je transfert ta demande ici : https://github.com/doudz/jeedom-plugin-zigate/issues/33
