### ISSUE TITLE
Erreur JavaScript

### ISSUE THREAD

**Issue by durdur33** [doudz/zigate#189]
Bonjour Doudz
depuis quelque semaine , j'ai une erreur  javascript lorsque je vais sur l'onglet Graphique du réseau

![image](https://user-images.githubusercontent.com/64473585/82936266-9a3bbc80-9f8e-11ea-9148-05a27f9780d3.png)

et rien ne s'affiche dans l'onglet graphique du réseau

![image](https://user-images.githubusercontent.com/64473585/82936378-c9522e00-9f8e-11ea-9a24-72e80c14daaf.png)

Merci
Didier

**Comment by doudz** [comment]
Mauvais endroit, merci d'utiliser https://github.com/jeedom-zigate/jeedom-plugin-zigate/issues
