### ISSUE TITLE
No response after command

### ISSUE THREAD

**Issue by ChoOo7** [doudz/zigate#24]
Hello

I have several output of this kind on my broker : 
python3 -m zigate.mqtt_broker --device auto --mqtt_host localhost:1883
INFO:zigate:Searching ZiGate port
INFO:zigate:ZiGate found at /dev/ttyUSB0
INFO:root:Publish zigate/device_changed/0cba
INFO:root:Publish zigate/device_changed/62ce
INFO:root:MQTT connected with result code 0
ERROR:zigate:No response after command 0x0042
ERROR:zigate:No response after command 0x0044
ERROR:zigate:No response after command 0x0045
INFO:root:Publish zigate/device_changed/be02
ERROR:zigate:No response after command 0x0042
ERROR:zigate:No response after command 0x0044
ERROR:zigate:No response after command 0x0045
INFO:root:Publish zigate/device_changed/ee65
ERROR:zigate:No response after command 0x0042
ERROR:zigate:No response after command 0x0044
ERROR:zigate:No response after command 0x0045
INFO:root:Publish zigate/device_changed/b89c
ERROR:zigate:No response after command 0x0042

ERROR:zigate:No response after command 0x0044
ERROR:zigate:No response after command 0x0045

During this period, I hit several times my button switch

After some time (more than 15 seconds) Appears informations related to my buttons : 

INFO:root:Publish zigate/attribute_changed/0cba/01/0006/0000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/0000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/0000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/0000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/8000
INFO:root:Publish zigate/attribute_changed/62ce/01/0000/0005
INFO:root:Publish zigate/attribute_changed/62ce/01/0000/ff01
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/0000
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/0000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/8000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/8000
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/0000
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/0000
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/8000
INFO:root:Publish zigate/attribute_changed/0cba/01/0006/8000
INFO:root:Publish zigate/attribute_changed/62ce/01/0006/8000

Why thoose error messages ?
Why this delay ?

Thanks

**Comment by doudz** [comment]
at start, we try to refresh de the device by sending many discovery commands.
Since the device doesn't reply, it produce error but this can be ignore safely

during this discovery, zigate is busy, many that's why there's a delay

**Comment by ChoOo7** [comment]
Indeed, after some times, button response is fine. Thanks
