### ISSUE TITLE
Calcul du % de batterie...

### ISSUE THREAD

**Issue by llaumgui** [doudz/zigate#25]
On a initié une discussion [ici](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/issues/47) mais la solution est à corriger dans la lib Python.

La problème est dans la décharge non linéaire des piles qui entraine une imprécision du suivie:
![44849076-39683e80-ac59-11e8-8a11-4214f17f1878](https://user-images.githubusercontent.com/411360/44975981-25c41d00-af64-11e8-89ef-34b7d2a07cb1.png)

**Comment by doudz** [comment]
Petite modification pour être plus réaliste https://github.com/doudz/zigate/commit/cb550a6e258a0229d6a03ebc5097abca172c121c
