### ISSUE TITLE
Pilotage ampoule Ikea tradfi

### ISSUE THREAD

**Issue by ChoOo7** [doudz/zigate#30]
Bonjour

J'ai essayé d'utiliser l'ampoule Ikea tradfi (variateur de "blanc") avec une zigate et ta librairie.

Je lance le broker, permet l'association et fait un factory reset de l'ampoule

Je vois bien dans mes traces : 

string(14) "zigate/command"
string(39) "{"function": "permit_join", "args": []}"

puis

string(26) "zigate/device_changed/f4c6"
string(130) "{"addr": "f4c6", "info": {"addr": "f4c6", "ieee": "90fd9ffffe8b41a6", "mac_capability": "10001110", "rssi": 150}, "endpoints": []}"

Je me dit, gagné, l'adresse est f4c6.
A minima je devrais pouvoir faire du on / off dessus (comme je le fait déjà pour mes bandeaux de led)

Ne connaissait pas le endpoint, et ne sachant pas trop comment le trouver, je fais donc un peu le bourrin pour le trouver : 

for($i=0; $i < 64; $i++)
{
sleep(1);
echo "\n$i";
$payload = '{"function": "action_onoff", "args": ["f4c6", '.$i.', 2]}';
$mqtt->publish("zigate/command", $payload, 0);
}

Je lance un toogle en testant tous les endpoints entre 0 et 64.
Mais là c'est le drame, l'ampoule ne change pas d'état :(

Merci pour l'aide

**Comment by doudz** [comment]
L'envoi de commande en "mode bourrin" est vrai déconseillé...
Je suggère 2 choses : 
- Faire un refresh pour être certain que l'ampoule a été correctement découverte:
$payload = '{"function": "refresh_device", "args": ["f4c6",]}';
- Récupérer la description complete de l'ampoule
$payload = '{"function": "get_device_from_addr", "args": ["f4c6",]}';

**Comment by ChoOo7** [comment]
Merci pour ces conseils

Je ne pense pas que l'ampoule ai été correctement découverte malheureusement.

Lorsque j'utilise f4c6, je n'ai jamais de réponse alors que sur d'autres dispositifs j'ai bien un retour.

Quelqu'un a piloté son ampoule Ikéa directement depuis la zigate ?

Merci

**Comment by doudz** [comment]
Que donne la fonction "devices" ? Tu devrais voir la liste des équipements.
De nombreuses personnes ont déjà réussi à piloter une ampoule IKEA, pour info cette lib python est utilisé par le plugin Jeedom "Zigate"

Pour info, les ampoules IKEA utilisent le endpoint 1

Attention, il peut y avoir des problèmes si tu utilises aussi la télécommande, il y a un ordre précis à respecter pour associer l'ampoule, la télécommande et la zigate.
Si l'ordre n'est pas respecté, soit la télécommande ne peut plus piloter l'ampoule, soit c'est la zigate qui ne peut plus.
Tu peux t'inspirer de cette procédure : 
https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/blob/master/docs/fr_FR/ikea.md

**Comment by ChoOo7** [comment]
Hummm
C'est mieux, mais c'est louche

J'ai mis la zigate en mode association et associé la télécommande -> ok
J'ai remis la zigate en mode association et associé l'ampoule -> ok
J'ai fait un refresh, et reussi à piloter l'ampoule (on off toogle) depuis la zigate -> ok

J'ai associé ma télécommande à mon ampoule -> ok

Tout roule ?
Non :'(
Sur ma télécommande j'ai 5 boutons
on/off - >ok
intensité lumineuse > ok
changement de scène (blanc -> jaune) -> NOT OK

Le changement de scène ne marche plus depuis que j'ai commencé la procédure (de ce ticket). Cela marchait avant. Lorsque j'appuie sur le bouton de ma télécommande, rien ne se passe :(
J'ai désassocié ma télécommande de l'ampoule et je l'ai associée de nouveau, cela n'aide pas.

Une idée ?

**Comment by ChoOo7** [comment]
Le souci est reproductible
J'ai reset la télécommande & l'ampoule, puis associé la télécommande à l'ampoule
=> Je peux de nouveau controler la scène (blanc / jaune)

J'ai associé la télécommande à la zigate, l'ampoule à la zigate, puis la télécommande à l'ampoule
=> Même symptôme, la télécommande n'est plus capable de piloter la scène :/
cc @fairecasoimeme

**Comment by doudz** [comment]
Impossible de répondre pour moi, il y a effectivement un souci mais je n'ai pas de matériel ikea et je n'utilise pas les scènes .
Je laisse l'issue ouvert pour le moment mais je pense que le souci vient de la zigate

**Comment by ChoOo7** [comment]
Merci pour ta réponse. J'ai sollicité @fairecasoimeme sur le github de la zigate.

**Comment by doudz** [comment]
Je clôture puisque le souci est côté zigate
