### ISSUE TITLE
Delete device question/problem

### ISSUE THREAD

**Issue by pawelka** [doudz/zigate#36]
In code remove device command is:
0026+ieee+ieee

commented one is:
0026+addr+ieee

On zigate site https://zigate.fr/wiki/commandes-zigate/ is commented version. 

Why you used ieee+ieee? I'm asking, because I don't know if it's by purpose or bug.

**Comment by doudz** [comment]
Well, the fact is I don't manage to make it works, that's why I tried both command

https://github.com/fairecasoimeme/ZiGate/issues/29
https://github.com/fairecasoimeme/ZiGate/issues/55

**Comment by doudz** [comment]
Should be fixed in 0.21.1

**Comment by biau** [comment]
this bug could explain this in hass?
2018-11-15 18:11:21 DEBUG (Thread-7) [zigate] Previous devices missing : {'207e', '07ca', 'dd8c', 'b746', '0097', 'ae25', '8065', '09c5', '06bd', '8a15', 'a3c3', '06f9', 'b40b', '36cd'}

Did you test 0.21.1 with hass ?

**Comment by ruimarinho** [comment]
@biau which plugin are you using for hass integration?

**Comment by doudz** [comment]
I suppose he use https://github.com/doudz/homeassistant-zigate

**Comment by ruimarinho** [comment]
Are you restarting development of the plugin? That would be fantastic! The community needs it :)

**Comment by doudz** [comment]
The github repo is not archived anymore ;)

**Comment by biau** [comment]
Yes that's devices I had to rejoin to the zigate and these addresses does not exist anymore.
Is there any command I can send to remove them? 

Great news for all zigate users and thanks for your work.

**Comment by doudz** [comment]
To remove this sévices, call cleanup
