### ISSUE TITLE
Fake clusters/endpoints. How to skip?

### ISSUE THREAD

**Issue by pawelka** [doudz/zigate#43]
Probably improvement is needed.

I'm using Xiaomi staff and I noticed that Aqara wall switch single button replay for endpoints which doesn't exists. For example this single key button work on endpoint 2 and endpoint 1 do nothing. Another example is wireless switch with responding for cluster 18 and to nothing.

Idea for improvement is to introduce device configuration file (aka file later). Device is configured per manufacturer and type.

I see two options :
1) file contains device clusters and endpoints if match to paired on configuration is used and if not autodiscovery applied as is
2) file contains only cluster & endpoints to exclude when scanning (deconz use exclusion in code, but easier will be have file)

I prefer first options because in case of pairing new device which exists adding will be fast because scan is not needed or mix 1) and 2) is possible.

This is needed for home-assistant plugin which creates entities automatically and in case of fake endpoints and clusters there are fake entities :-/

**Comment by doudz** [comment]
Until now I was opposed to create such files, because autodiscovery able to support virtually any device.
But yes, there's limitation.
Maybe we can do both, use file for known device and autodiscovery when needed
