### ISSUE TITLE
Vibration sensor events

### ISSUE THREAD

**Issue by ruimarinho** [doudz/zigate#56]
Looking at the screenshot from [faire-ca-soi-meme](http://faire-ca-soi-meme.fr/domotique/2018/09/03/test-xiaomi-aqara-vibration-sensor/), I think https://github.com/doudz/zigate/blob/d3280c5cfe8a1bc2f03dabe4a5829bcdf6fb5ae8/zigate/clusters.py#L298 is actually "touched" (the message on the official app appears to be _the object has been touched_).

If you agree with this change, I can submit a PR.

**Comment by doudz** [comment]
ok, I'll change it to touched, thanks
