### ISSUE TITLE
Negative temperature problem with Xiaomi sensor

### ISSUE THREAD

**Issue by Jsl-1** [doudz/zigate#73]
Hi @doudz,

Negative temperatures seems positive  in ha with Xiaomi round sensors. I guess it's a problem on the library.
@pipiche38 seems to have fixed a similar problem with domoticz (https://www.domoticz.com/forum/viewtopic.php?t=26254).

Thank you very much for your huge investment in Zigate support.

**Comment by doudz** [comment]
It's a bit strange, could you provide some debug log ?

**Comment by Jsl-1** [comment]
Yes, as soon as negative temp append ;)
Don't have enough log for now. Maybe tomorrow or tuesday.

**Comment by ChoOo7** [comment]
Put it in the freezer !

**Comment by Jsl-1** [comment]
I'm suprised to have enough signal in the freezer, but it's working. And in fact there is no problem, ha reports negative correctly. There should be another problem with the sensor. Will investigate.
Sorry for  making you waste your time and thanks you again for your work and your help...
